image: haxe:4.0-stretch

before_script:
- haxelib install all

test:
  stage: test
  script:
  - apt-get update
  - apt-get install -yqq nodejs
  - haxelib install utest
  - haxe test.hxml
