image: haxe:4.0-stretch

stages:
- build-test
- deploy

build-cs:
  stage: build-test
  variables:
    HXML: hxml/build-cs.hxml
  script:
  - haxelib install $HXML --always --quiet
  - haxe $HXML

test-neko:
  stage: build-test
  retry: 2
  variables:
    HXML: test-neko.hxml
  script:
  - haxelib install $HXML --always --quiet
  - haxe $HXML

test-cpp:
  stage: build-test
  retry: 2
  variables:
    HXML: test-cpp.hxml
  script:
  - apt-get update
  - apt-get install -yqq build-essential g++
  - haxelib install $HXML --always --quiet
  - haxe $HXML

deploy:
  stage: deploy
  before_script:
  - apt-get update
  - apt-get install -yqq zip
  script:
  - mkdir -p build
  - zip -r build/udprotean.zip -@ < haxelib.lst
