image: haxe:4.0-stretch

cache:
  paths:
  - .haxelib/

before_script:
- haxelib newrepo
- haxelib install all --always --quiet

test-neko:
  stage: test
  script:
  - haxe test-neko.hxml

test-cpp:
  stage: test
  script:
  - apt-get update
  - apt-get install -yqq build-essential g++
  - haxe test-cpp.hxml
