image: haxe:4.0-stretch

cache:
  paths:
  - /haxelib/

test-neko:
  stage: test
  script:
  - haxelib install --always --quiet test-neko.hxml
  - haxe test-neko.hxml

test-cpp:
  stage: test
  script:
  - haxelib install --always --quiet test-cpp.hxml
  - apt-get update
  - apt-get install -yqq build-essential g++
  - haxe test-cpp.hxml
