image: haxe:4.0-stretch

cache:
  paths:
  - /haxelib/

before_script:
- haxelib install all --always

test:
  stage: test
  script:
  - apt-get update
  - apt-get install -yqq build-essential g++
  - haxe test.hxml
